//
//  MessagesViewController.swift
//  MessagesExtension
//
//  Created by Christopher Trott on 6/14/16.
//  Copyright © 2016 twocentstudios. All rights reserved.
//

import UIKit
import Messages

class MessagesViewController: MSMessagesAppViewController, MessagesViewDelegate {
    @IBOutlet weak var messagesView: MessagesView!
    
    var pair: Pair?
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        messagesView.delegate = self
        // Do any additional setup after loading the view.
    }
    
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    
    // MARK: - Conversation Handling
    
    override func willBecomeActive(with conversation: MSConversation) {
        // Called when the extension is about to move from the inactive to active state.
        // This will happen when the extension is about to present UI.
        
        // Use this method to configure the extension and restore previously stored state.
        pair = Pair(conversation: conversation)
        let viewState = ViewState(pair: pair)
        messagesView.viewState = viewState
    }
    
    override func didResignActive(with conversation: MSConversation) {
        // Called when the extension is about to move from the active to inactive state.
        // This will happen when the user dissmises the extension, changes to a different
        // conversation or quits Messages.
        
        // Use this method to release shared resources, save user data, invalidate timers,
        // and store enough state information to restore your extension to its current state
        // in case it is terminated later.
    }
   
    override func didReceive(_ message: MSMessage, conversation: MSConversation) {
        // Called when a message arrives that was generated by another instance of this
        // extension on a remote device.
        
        // Use this method to trigger UI updates in response to the message.
    }
    
    override func didStartSending(_ message: MSMessage, conversation: MSConversation) {
        // Called when the user taps the send button.
    }
    
    override func didCancelSending(_ message: MSMessage, conversation: MSConversation) {
        // Called when the user deletes the message without sending it.
    
        // Use this to clean up state related to the deleted message.
    }
    
    override func willTransition(to presentationStyle: MSMessagesAppPresentationStyle) {
        // Called before the extension transitions to a new presentation style.
        
        switch presentationStyle {
        case .compact:
            // Reset to .promptNew on collapse.
            let newPair: Pair? = nil
            let newViewState = ViewState(pair: newPair)
            self.pair = newPair
            self.messagesView.viewState = newViewState
        case .expanded:
            break
        }
    }
    
    override func didTransition(to presentationStyle: MSMessagesAppPresentationStyle) {
        // Called after the extension transitions to a new presentation style.
    
        // Use this method to finalize any behaviors associated with the change in presentation style.
    }
    
    // MARK: MessagesViewDelegate
    
    func didAction(_ view: MessagesView, action: ViewAction, state: ViewState) {
        let newPair = action.combine(withPair: self.pair)
        let newViewState = ViewState(pair: newPair)
        
        switch newViewState {
        case .promptNew:
            break // This is an unexpected case.
        case .translationNew, .correctionNew:
            requestPresentationStyle(.expanded)
        default:
            guard let conversation = activeConversation else { fatalError("Expected a conversation") }
            let session = conversation.selectedMessage?.session ?? MSSession()
            guard let message = newPair.composeMessage(session) else { fatalError("Expected a message") }
            let changeDescription = state.changeDescription()
            conversation.insert(message, localizedChangeDescription: changeDescription) { error in
                if let error = error {
                    fatalError("Message could not be inserted into conversation: \(error)") // TODO: investigate when this happens
                }
            }
            dismiss()
        }
        
        self.pair = newPair
        self.messagesView.viewState = newViewState
        
    }
    
}

